const mangaData = {
    title: "Made in Abyss",
    chapters: [
        [1, "Orth: The City of the Great Pit"],
    [2, "The Abode of Trees and Fossils"],
    [3, "Riko's Room: Former Torture Chamber"],
    [4, "Belchero Orphanage"],
    [5, "Resurrection Festival"],
    [6, "Premonition"],
    [7, "Eve of Departure"],
    [8, "Here We Go!"],
    [9, "The Depths' First Layer: The Edge of the Abyss"],
    [10, "The Depths' Second Layer: The Forest of Temptation"],
    [11, "Incinerator"],
    [12, "Lowest Area of the Depths' Second Layer: The Inverted Forest"],
    [13, "Seeker Camp"],
    [14, "The Curse-Repelling Vessel"],
    [15, "The Unmovable Sovereign"],
    [16, "A Vile Mentoring Method"],
    [17, "Survival Training"],
    [18, "The Depths' Third Layer: The Great Fault"],
    [19, "Poison and the Curse"],
    [20, "Nanachi"],
    [21, "Reg's Memories"],
    [22, "The True Nature of the Curse"],
    [23, "A Dreadful Experiment"],
    [24, "Liberation of the Soul"],
    [25, "A Return From Darkness"],
    [26, "A Fresh Start"],
    [27, "The Forbidden Field of Flowers"],
    [28, "The Entrance to the Sixth Layer"],
    [29, "A Fateful Reunion"],
    [30, "Unforeseen Peril"],
    [31, "Despair and Hope"],
    [32, "The End of a Fierce Fight"],
    [33, "The True Nature of the Mask"],
    [34, "Counterattack"],
    [35, "Clouded Memory"],
    [36, "Miniature Garden of Dawn"],
    [37, "Flower of Dawn"],
    [38, "The Challengers"],
    [39, "Capital of the Unreturned"],
    [40, "Hollow Husk of Life"],
    [41, "The Balancing of Values"],
    [42, "Princess of the Hollows"],
    [43, "Approaching Crisis"],
    [44, "Hollows' Restaurant"],
    [45, "Captive"],
    [46, "The Luring"],
    [47, "The Secret of the Village"],
    [48, "The Compass Pointed to the Darkness"],
    [49, "The Golden City"],
    [50, "The Cradle of Desire"],
    [51, "The Form the Wish Takes"],
    [52, "Faputa's Promise"],
    [53, "Prelude of Disintegration"],
    [54, "All That You Gather"],
    [55, "Faputa and Reg"],
    [56, "A Gift"],
    [57, "Value"],
    [58, "Towards the Path of Flame"],
    [59, "A Warm Darkness"],
    [60, "Gold"],
    [61, "You Can Go Anywhere"],
    [62, "The Place of Song"],
    [63, "The Curse Fleet - Prologue"],
    [64, "Juusou"],
    [65, "In the Midst"],
    [66, "Bottom Layer"],
    [67, "Whereabouts of the Soul"],
    [68, "Maelstrom Danger Zone - Part 1"],
    [69, "Maelstrom Danger Zone - Part 2"]
    ],
    volumes: [
        [1, 1], [9, 2], [17, 3], [25, 4], [33, 5], [38.5, 6],
        [43, 7], [48, 8], [52, 9], [56, 10], [61, 11], [64, 12], [67, 13]
    ],
    arcs: [
        [1, "Orth"],
        [9, "Descent to the Abyss"],
        [13, "Seeker Camp"],
        [18, "The Great Fault"],
        [19, "Poison and Liberation"],
        [27, "Ido Front"],
        [39, "Iruburu"],
        [61, "Capital of Unreturned"]
    ]
};
